lib/layouts_web/router.ex
defmodule LayoutsWeb.Router do
  use LayoutsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LayoutsWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/dashboard", DashboardController, :index

    get "/user", UserController, :index

  end

  # Other scopes may use custom stacks.
  # scope "/api", LayoutsWeb do
  #   pipe_through :api
  # end
end

lib/layouts/application.ex
defmodule Layouts.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Layouts.Repo,
      # Start the endpoint when the application starts
      LayoutsWeb.Endpoint
      # Starts a worker by calling: Layouts.Worker.start_link(arg)
      # {Layouts.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Layouts.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    LayoutsWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/layouts/repo.ex
defmodule Layouts.Repo do
  use Ecto.Repo,
    otp_app: :layouts,
    adapter: Ecto.Adapters.Postgres
end

lib/layouts_web/controllers/page_controller.ex
defmodule LayoutsWeb.PageController do
  use LayoutsWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/layouts_web/controllers/user_controller.ex
defmodule LayoutsWeb.UserController do
  use LayoutsWeb, :controller

  def index(conn, _params) do
    render(conn, "user.html")
  end

end

lib/layouts_web/views/dashboard_view.ex
defmodule LayoutsWeb.DashboardView do
  use LayoutsWeb, :view
end

lib/layouts_web/views/error_view.ex
defmodule LayoutsWeb.ErrorView do
  use LayoutsWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/layouts_web/views/layout_view.ex
defmodule LayoutsWeb.LayoutView do
  use LayoutsWeb, :view
end

lib/layouts_web/views/page_view.ex
defmodule LayoutsWeb.PageView do
  use LayoutsWeb, :view
end

lib/layouts_web/views/user_view.ex
defmodule LayoutsWeb.UserView do
  use LayoutsWeb, :view
end

lib/layouts_web/templates/dashboard/dashboard.html.eex
<%= link "Go to user page", class: "btn btn-success", to: Routes.user_path(@conn, :index) %>



<style>
.footer {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: grey;
  color: white;
  text-align: center;
}
</style>

<div class="footer">
  <p>by @musa</p>
</div>

lib/layouts_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Layouts · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
  </head>

  <body>
    <header>
      <div class="header">
        <h1>Header</h1>
      </div>

      <div class="sidenav">
        <a href="#">side_nav</a>
      </div>
    </header>

    
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/layouts_web/templates/page/index.html.eex
<%= link "Go to user page", class: "btn btn-success", to: Routes.user_path(@conn, :index) %><br>
<br><br>
<%= link "Go to dashboard", class: "btn btn-success", to: Routes.dashboard_path(@conn, :index) %>



<style>

.footer {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: grey;
  color: white;
  text-align: center;
}


</style>

<div class="footer">
  <p>by @musa</p>
</div>

lib/layouts_web/templates/user/user.html.eex
<%= link "Back to the Dashboard", class: "btn btn-success", to: Routes.dashboard_path(@conn, :index) %>




<style>
.footer {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: grey;
  color: white;
  text-align: center;
}
</style>

<div class="footer">
  <p>by @musa</p>
</div>